type TeamLogoProps = {
  name: string;
  size?: number;
};

const localLogos: Record<string, string> = {
  Alavés: '/assets/teams/deportivo-alaves-logo-footylogos.svg',
  Albacete: '/assets/teams/albacete-balompie-logo-footylogos.svg',
  Almería: '/assets/teams/ud-almeria-logo-footylogos.svg',
  'Athletic Club': '/assets/teams/athletic-club-bilbao-logo-footylogos.svg',
  'Atlético Madrid': '/assets/teams/atletico-madrid-logo-footylogos.svg',
  Cádiz: '/assets/teams/cadiz-cf-logo-footylogos.svg',
  Celta: '/assets/teams/celta-vigo-logo-footylogos.svg',
  'Celta Vigo': '/assets/teams/celta-vigo-logo-footylogos.svg',
  Compostela: '/assets/teams/sd-compostela-logo-footylogos.svg',
  Córdoba: '/assets/teams/cordoba-logo-footylogos.svg',
  Deportivo: '/assets/teams/deportivo-la-coruna-logo-footylogos.svg',
  Eibar: '/assets/teams/sd-eibar-logo-footylogos.svg',
  Elche: '/assets/teams/elche-cf-logo-footylogos.svg',
  Espanyol: '/assets/teams/rcd-espanyol-barcelona-logo-footylogos.svg',
  Extremadura: '/assets/teams/cd-extremadura-logo-footylogos.svg',
  Gimnastic: '/assets/teams/gimnastic-de-tarragona-logo-footylogos.svg',
  Girona: '/assets/teams/girona-fc-logo-footylogos.svg',
  Granada: '/assets/teams/granada-logo-footylogos.svg',
  Hércules: '/assets/teams/hercules-de-alicante-cf-logo-footylogos.svg',
  Getafe: '/assets/teams/getafe-cf-logo-footylogos.svg',
  'Las Palmas': '/assets/teams/las-palmas-logo-footylogos.svg',
  Leganes: '/assets/teams/cd-leganes-logo-footylogos.svg',
  Lerida: '/assets/teams/3658_ue-lleida-logo.png',
  Levante: '/assets/teams/levante-ud-logo-footylogos.svg',
  Logrones: '/assets/teams/sd-logrones-logo-footylogos.svg',
  Málaga: '/assets/teams/malaga-cf-logo-footylogos.svg',
  Mallorca: '/assets/teams/rcd-mallorca-logo-footylogos.svg',
  Merida: '/assets/teams/ad-merida-logo-footylogos.svg',
  Murcia: '/assets/teams/real-murcia-cf-logo-footylogos.svg',
  Numancia: '/assets/teams/numancia-logo-footylogos.svg',
  Osasuna: '/assets/teams/osasuna-logo-footylogos.svg',
  Oviedo: '/assets/teams/real-oviedo-logo-footylogos.svg',
  'Racing Santander': '/assets/teams/racing-santander-logo-footylogos.svg',
  'Rayo Vallecano': '/assets/teams/rayo-vallecano-logo-footylogos.svg',
  Vallecano: '/assets/teams/rayo-vallecano-logo-footylogos.svg',
  'Real Betis': '/assets/teams/real-betis-balompie-logo-footylogos.svg',
  'Real Sociedad': '/assets/teams/real-sociedad-logo-footylogos.svg',
  Recreativo: '/assets/teams/recreativo-huelva-logo-footylogos.svg',
  Salamanca: '/assets/teams/unionistas-de-salamanca-cf-logo-footylogos.svg',
  Sevilla: '/assets/teams/sevilla-fc-logo-footylogos.svg',
  'Sporting Gijón': '/assets/teams/sporting-gijon-logo-footylogos.svg',
  Valencia: '/assets/teams/valencia-cf-logo-footylogos.svg',
  Valladolid: '/assets/teams/real-valladolid-logo-footylogos.svg',
  Villareal: '/assets/teams/villarreal-cf-logo-footylogos.svg',
  Villarreal: '/assets/teams/villarreal-cf-logo-footylogos.svg',
  Xerez: '/assets/teams/xerez-cd-logo-footylogos.svg',
  Zaragoza: '/assets/teams/real-zaragoza-logo-footylogos.svg',
  Sampdoria: '/assets/teams/uc-sampdoria-logo-footylogos.svg',
  Juventus: '/assets/teams/juventus-logo-footylogos.svg',
  Arsenal: '/assets/teams/arsenal-logo-footylogos.svg',
  'FC Barcelona': '/assets/teams/fc-barcelona.svg',
  'Real Madrid': '/assets/teams/real-madrid.svg',
  'Manchester United': '/assets/teams/manchester-united.svg',
  'Paris Saint-Germain': '/assets/teams/paris-saint-germain.svg',
};

const crestTitles: Record<string, string> = {
  Alavés: 'Deportivo Alavés crest.svg',
  Albacete: 'Albacete Balompié logo.svg',
  Almería: 'UD Almería logo.svg',
  'Athletic Club': 'Athletic Club Bilbao logo.svg',
  'Atlético Madrid': 'Atlético Madrid crest.svg',
  Cádiz: 'Cádiz CF logo.svg',
  Córdoba: 'Córdoba CF logo.svg',
  Celta: 'RC Celta de Vigo logo.svg',
  Compostela: 'SD Compostela logo.svg',
  Deportivo: 'Deportivo de La Coruña logo.svg',
  Eibar: 'SD Eibar logo.svg',
  Elche: 'Elche CF crest.svg',
  Espanyol: 'RCD Espanyol logo.svg',
  Extremadura: 'Extremadura UD logo.svg',
  Getafe: 'Getafe CF logo.svg',
  Gimnastic: 'Gimnàstic de Tarragona logo.svg',
  Girona: 'Girona FC logo.svg',
  Granada: 'Granada CF logo.svg',
  Hércules: 'Hércules CF logo.svg',
  Huesca: 'SD Huesca logo.svg',
  'Las Palmas': 'UD Las Palmas logo.svg',
  Leganes: 'CD Leganés logo.svg',
  Lerida: 'UE Lleida logo.svg',
  Levante: 'Levante UD logo.svg',
  Logrones: 'CD Logroñés logo.svg',
  Málaga: 'Málaga CF logo.svg',
  Mallorca: 'RCD Mallorca logo.svg',
  Merida: 'CP Mérida logo.svg',
  Murcia: 'Real Murcia logo.svg',
  Numancia: 'CD Numancia logo.svg',
  Osasuna: 'CA Osasuna logo.svg',
  Oviedo: 'Real Oviedo logo.svg',
  'Racing Santander': 'Racing de Santander logo.svg',
  'Rayo Vallecano': 'Rayo Vallecano logo.svg',
  'Real Betis': 'Real Betis logo.svg',
  'Real Sociedad': 'Real Sociedad logo.svg',
  Recreativo: 'Recreativo de Huelva logo.svg',
  Salamanca: 'UD Salamanca logo.svg',
  Sevilla: 'Sevilla FC logo.svg',
  'Sporting Gijón': 'Sporting de Gijón logo.svg',
  Tenerife: 'CD Tenerife logo.svg',
  Valencia: 'Valencia CF logo.svg',
  Valladolid: 'Real Valladolid logo.svg',
  Vallecano: 'Rayo Vallecano logo.svg',
  Villareal: 'Villarreal CF logo.svg',
  Villarreal: 'Villarreal CF logo.svg',
  Xerez: 'Xerez CD logo.svg',
  Zaragoza: 'Real Zaragoza logo.svg',
  Sampdoria: 'UC Sampdoria logo.svg',
  Juventus: 'Juventus FC logo.svg',
};

function remoteLogo(name: string) {
  const title = crestTitles[name] ?? `${name} logo.svg`;
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(title)}`;
}

export function TeamLogo({ name, size = 54 }: TeamLogoProps) {
  return <img className="team-logo" src={localLogos[name] ?? remoteLogo(name)} width={size} height={size} alt={`${name} crest`} loading="lazy" />;
}
